Aide_Text_HaventCaughtEnoughMonsForItem::
	.string "Vejamos…\n"
	.string "Ah não! Você só capturou\l"
	.string "{STR_VAR_3} tipos de POKéMON!\p"
	.string "Você precisa de {STR_VAR_1} tipos\n"
	.string "se quiser o item {STR_VAR_2}.$"

Aide_Text_GetEnoughMonsComeBackForItem::
	.string "…Ah. Entendi.\p"
	.string "Quando pegar {STR_VAR_1} tipos de POKéMON,\n"
	.string "volte pegar o item {STR_VAR_2}.$"

Aide_Text_DontHaveAnyRoomForItem::
	.string "Ah! você não tem espaço para\n"
	.string "guardar o item {STR_VAR_2}.$"
