Braille_Text_Up::
	.braille "CIMA$"

Braille_Text_Down::
	.braille "BAIXO$"

Braille_Text_Right::
	.braille "DIREITA$"

Braille_Text_Left::
	.braille "ESQUERDA$"

Braille_Text_Cut::
	.braille "CORTAR$"

Braille_Text_ABC::
	.braille "ABC$"

Braille_Text_GHI::
	.braille "GHI$"

Braille_Text_MNO::
	.braille "MNO$"

Braille_Text_TUV::
	.braille "TUV$"

Braille_Text_DEF::
	.braille "DEF$"

Braille_Text_JKL::
	.braille "JKL$"

Braille_Text_PQRS::
	.braille "PQRS$"

Braille_Text_WXYZ::
	.braille "WXYZ$"

Braille_Text_Period::
	.braille ".$"

Braille_Text_Comma::
	.braille ",$"

Braille_Text_Everything::
	.braille "TUDO TEM$"

Braille_Text_HasMeaning1::
	.braille "SENTIDO,$"

Braille_Text_Existence::
	.braille "VIVER TEM$"

Braille_Text_HasMeaning2::
	.braille "SENTIDO,$"

Braille_Text_BeingAlive::
	.braille "EXISTIR$"

Braille_Text_HasMeaning3::
	.braille "TAMBEM,$"

Braille_Text_HaveDreams::
	.braille "SONHE,$"

Braille_Text_UsePower::
	.braille "USE PODER.$"

Braille_Text_LetTheTwo::
	.braille "QUE DUAS$"

Braille_Text_Glittering::
	.braille "PEDRAS$"

Braille_Text_Stones::
	.braille "BRILHANTES$"

Braille_Text_OneInRed::
	.braille "VERMELHA$"

Braille_Text_OneInBlue::
	.braille "E AZUL,$"

Braille_Text_ConnectThe::
	.braille "CONECTEM O$"

Braille_Text_Past::
	.braille "PASSADO.$"

Braille_Text_TwoFriends::
	.braille "OS AMIGOS$"

Braille_Text_Sharing::
	.braille "QUE USAM$"

Braille_Text_PowerOpen::
	.braille "O PODER$"

Braille_Text_AWindowTo::
	.braille "ABREM A$"

Braille_Text_ANewWorld::
	.braille "JANELA AO$"

Braille_Text_ThatGlows::
	.braille "NOVO MUNDO$"

Braille_Text_TheNext::
	.braille "QUE ESPERA$"

Braille_Text_WorldWaits::
	.braille "ANSIOSO$"

Braille_Text_ForYou::
	.braille "POR VOCES.$"
