@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "Está cheia de livros sobre\n"
	.string "POKéMON.$"

Text_NothingButPokemonBooks::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap::
	.string "Um MAPA DA ÁREA.$"

Text_PokeMartShelf::
	.string "Nossa!\n"
	.string "Quantas coisas de POKéMON!$"

Text_DishesPlatesNeatlyLinedUp::
	.string "As louças estão muito bem\n"
	.string "organizadas.$"

Text_Kitchen::
	.string "Está com um cheiro bom!\n"
	.string "Alguém anda cozinhando.$"

Text_Dresser::
	.string "É uma cômoda bem feita.\n"
	.string "Pode suportar várias coisas.$"

Text_Snacks::
	.string "There's a pile of snacks here.$"

Text_PokemartSign::
	.string "All your item needs fulfilled!\n"
	.string "POKéMON MART$"

Text_PokecenterSign::
	.string "Heal Your POKéMON!\n"
	.string "POKéMON CENTER$"

Text_Indigo_UltimateGoal::
	.string "INDIGO PLATEAU\p"
	.string "The ultimate goal of TRAINERS!\n"
	.string "POKéMON LEAGUE HQ$"

Text_Indigo_HighestAuthority::
	.string "INDIGO PLATEAU\p"
	.string "The highest POKéMON authority!\n"
	.string "POKéMON LEAGUE HQ$"

Text_Food::
	.string "It should be packed with all kinds\n"
	.string "of delicious things to eat.$"

Text_Blueprints::
	.string "It's a blueprint of some sort.\n"
	.string "It's filled with diagrams and text.$"

Text_Painting::
	.string "It's a pretty picture of a POKéMON.\n"
	.string "It looks like it's feeling good.$"

Text_PowerPlantMachine::
	.string "What could this machine be?\n"
	.string "Better not mess around with it!$"

Text_Telephone::
	.string "It's a telephone.\n"
	.string "Better not use it.$"

Text_Computer::
	.string "It's all complicated words and\n"
	.string "numbers that make no sense…$"

Text_AdvertisingPoster::
	.string "It's an advertising poster about\n"
	.string "all kinds of products.$"

Text_TastyFood::
	.string "Oh, that smells tasty!\n"
	.string "It might get the stomach growling!$"

Text_TrashBin::
	.string "Inside this…\n"
	.string "……\p"
	.string "There's nothing here!$"

Text_Cup::
	.string "It's a cup with a POKéMON mark\n"
	.string "on it.$"

Text_PolishedWindow::
	.string "The window is very well polished.$"

Text_BeautifulSkyWindow::
	.string "Outside the window…\p"
	.string "The sky looks fantastically\n"
	.string "beautiful.$"

Text_BlinkingLights::
	.string "Lights in different colors are\n"
	.string "flashing on and off.$"

Text_NeatlyLinedUpTools::
	.string "All sorts of tools are lined up\n"
	.string "neatly.$"

Text_ImpressiveMachine::
	.string "It's a machine of some sort.\n"
	.string "It sure is impressive.$"

Text_VideoGame::
	.string "It's the latest video game!\n"
	.string "It sure looks fun!$"

Text_Burglary::
	.string "There are obvious signs of burglary\n"
	.string "here…$"

Text_PlayerFacingTVScreen::
	.string "There's a POKéMON on TV!\n"
	.string "It looks like it's having fun.$"
