gOtherText_NewName::
    .string "NOVO NOME$"

gNameChoice_Green::
    .string "GREEN$"

gNameChoice_Red::
    .string "RED$"

gNameChoice_Leaf::
    .string "LEAF$"

gNameChoice_Fire::
    .string "FIRE$"

gNameChoice_Gary::
    .string "GARY$"

gNameChoice_Kaz::
    .string "KAZ$"

gNameChoice_Toru::
    .string "TORU$"

gNameChoice_Ash::
    .string "ASH$"

gNameChoice_Kene::
    .string "KENNY$"

gNameChoice_Geki::
    .string "STAN$"

gNameChoice_Jak::
    .string "KYLE$"

gNameChoice_Janne::
    .string "JOSÉ$"

gNameChoice_Jonn::
    .string "TOMÉ$"

gNameChoice_Kamon::
    .string "SORA$"

gNameChoice_Karl::
    .string "KARLOS$"

gNameChoice_Taylor::
    .string "JEAN$"

gNameChoice_Oscar::
    .string "OSCAR$"

gNameChoice_Hiro::
    .string "HIRO$"

gNameChoice_Max::
    .string "MAX$"

gNameChoice_Jon::
    .string "JOÃO$"

gNameChoice_Ralph::
    .string "RAFAEL$"

gNameChoice_Kay::
    .string "LUCAS$"

gNameChoice_Tosh::
    .string "MATHEUS$"

gNameChoice_Roak::
    .string "JÚLIO$"

gNameChoice_Omi::
    .string "JENNY$"

gNameChoice_Jodi::
    .string "LUÍSA$"

gNameChoice_Amanda::
    .string "AMANDA$"

gNameChoice_Hillary::
    .string "TERESA$"

gNameChoice_Makey::
    .string "MARIA$"

gNameChoice_Michi::
    .string "LIZA$"

gNameChoice_Paula::
    .string "PAULA$"

gNameChoice_June::
    .string "JANA$"

gNameChoice_Cassie::
    .string "SÔNIA$"

gNameChoice_Rey::
    .string "GI$"

gNameChoice_Seda::
    .string "FEFÊ$"

gNameChoice_Kiko::
    .string "PÓPIS$"

gNameChoice_Mina::
    .string "MINA$"

gNameChoice_Norie::
    .string "LUANE$"

gNameChoice_Sai::
    .string "THATÁ$"

gNameChoice_Momo::
    .string "MOMO$"

gNameChoice_Suzi::
    .string "SUZI$"

gControlsGuide_Text_Intro::
    .string "Os diversos botões serão explicados\n"
	.string "em ordem de importância.$"

gControlsGuide_Text_DPad::
    .string "Movimenta a personagem.\n"
    .string "Também usado para escolher\n"
    .string "dentre dados variados.$"

gControlsGuide_Text_AButton::
    .string "Use para confirmar uma escolha,\n"
    .string "examinar, conversar ou ler texto.$"

gControlsGuide_Text_BButton::
    .string "Use para sair, cancelar escolhas\n"
    .string "ou cancelar um modo.$"

gControlsGuide_Text_StartButton::
    .string "Aperte este botão para abrir\n"
    .string "o MENU.$"

gControlsGuide_Text_SelectButton::
    .string "Use para mover itens ou para\n"
    .string "usar um item marcado.$"

gControlsGuide_Text_LRButtons::
    .string "Se precisar de ajuda sobre como\n"
    .string "jogar o jogo, ou fazer coisas,\n"
    .string "aperte o botão L ou R.$"

gOakSpeech_Text_AskPlayerGender::
    .string "Agora diga-me. Você é um garoto?\n"
    .string "Ou você é uma garota?$"

gPikachuIntro_Text_Page1::
	.string "O mundo em que você está prestes a\n"
	.string "embarcar será uma grande aventura na\n"
	.string "qual você é a personagem principal.\n"
	.string "\n"
	.string "Fale com gente e examine coisas aonde\n"
	.string "for que vá, sejam cidades, estradas ou\n"
	.string "cavernas. Colete informações e dicas\n"
	.string "de todas as origens.$"

gPikachuIntro_Text_Page2::
	.string "Novas oportunidades se abrirão se\n"
	.string "ajudar pessoas necessitadas, superar\n"
	.string "desafios e resolver mistérios.\n"
	.string "\n"
	.string "Às vezes, os outros te desafiarão, até\n"
	.string "mesmo criaturas selvagens te atacarão.\n"
	.string "\n"
	.string "Tenha coragem e siga em frente.$"

gPikachuIntro_Text_Page3::
	.string "Através dessa aventura, esperamos que\n"
	.string "você interaja com todo tipo de pessoa\n"
	.string "e adquira crescimento pessoal.\n"
	.string "Este é nosso grande objetivo.\n"
	.string "\n"
	.string "\n"
	.string "Agora aperte o botão A, e que sua\n"
	.string "aventura comece!$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "Olá, como vai?\n"
    .string "Prazer em te conhecer!\p"
    .string "Boas-vindas ao mundo POKéMON!\p"
    .string "Meu nome é CARVALHO.\p"
	.string "As pessoas carinhosamente me chamam\n"
	.string "de PROFESSOR POKéMON.\p$"

gOakSpeech_Text_ThisWorld::
    .string "Este mundo…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
	.string "…é povoado lá e cá de criaturas\n"
	.string "chamadas de POKéMONS.\p$"

gOakSpeech_Text_IStudyPokemon::
	.string "Para alguns, POKéMONS são como\n"
	.string "bichinhos de estimação.\l"
	.string "Outros os usam para batalhar.\p"
	.string "Já eu…\p"
	.string "Eu estudo POKéMONS.\n"
	.string "Esta é minha profissão.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
	.string "Mas antes de tudo, deixe-me te\n"
	.string "conhecer primeiro.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
	.string "Comecemos pelo seu nome.\n"
	.string "Qual é?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
	.string "Certo…\n"
	.string "Então seu nome é {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
	.string "Este é meu neto.\p"
	.string "Ele foi seu rival desde que ambos\n"
	.string "eram só nenéns.\p"
	.string "…Éee, qual era o nome dele mesmo?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
	.string "O nome do seu rival, qual era mesmo?$"

gOakSpeech_Text_ConfirmRivalName::
	.string "…Hum, será que era {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
	.string "Ah, é! Lembrei!\n"
	.string "O nome dele é {RIVAL}!\p$"

gOakSpeech_Text_LetsGo::
    .string "{PLAYER}!\p"
	.string "Sua própria lenda POKéMON está\n"
	.string "prestes a se desdobrar!\p"
	.string "Um mundo de sonhos e aventuras\n"
	.string "POKéMON te espera! Vamos lá!$"
