Text_MayIHelpYou::
	.string "Olá!\n"
	.string "Como posso ajudar?$"

Text_FillOutQuestionnaire::
	.string "Há um questionário.\n"
	.string "Você quer preenchê-lo?$"

Text_QuestionnaireThankYou::
	.string "Agradecemos por dedicar seu tempo\n"
	.string "para preencher o questionário.\p"
	.string "Sua opinião será guardada e usada\n"
	.string "como referência no futuro.$"

Text_YouKnowThoseWords::
	.string "Ah, olá!\n"
	.string "Você conhece essas palavras?\p"
	.string "Significa que já deve conhecer\n"
	.string "o PRESENTE MISTERIOSO.\p"
	.string "Daqui em diante, você pode estar\n"
	.string "recebendo PRESENTES MISTERIOSOS!$"

Text_YouCanAccessMysteryGift::
	.string "Assim que salvar o jogo, você pode\n"
	.string "acessar o PRESENTE MISTERIOSO.$"

Text_ThankYouForAccessingMysteryGift::
	.string "Thank you for accessing the\n"
	.string "MYSTERY GIFT System.$"
