gText_WouldYouLikeToSaveTheGame::
	.string "Gostaria de salvar o jogo?$"

gText_AlreadySaveFile_WouldLikeToOverwrite::
	.string "Já existe um arquivo salvo.\n"
	.string "Tudo bem sobrescrevê-lo?$"

gText_SavingDontTurnOffThePower::
	.string "SALVANDO…\n"
	.string "NÃO DESLIGUE O VIDEO GAME.$"

gText_PlayerSavedTheGame::
	.string "{PLAYER} salvou o jogo.$"

gText_SaveFailed2::
	.string "セーブに　しっぱい　しました‥$"

gText_DifferentGameFile::
	.string "ATENÇÃO!\p"
	.string "Há um arquivo de jogo diferente que\n"
	.string "já está salvo.\p"
	.string "Se salvar agora, a aventura do outro\n"
	.string "arquivo, inclusive itens e POKéMON, será\n"
	.string "completamente perdida.\p"
	.string "Tem certeza que quer salvar agora e\n"
	.string "sobrescrever o outro arquivo?$"
