LavenderTown_PokemonCenter_1F_Text_RocketsDoAnythingForMoney::
    .string "TEAM ROCKET will do anything for\n"
    .string "the sake of money!\p"
    .string "There is no job too dirty, no deed\n"
    .string "too heinous, no crime too wicked!$"

LavenderTown_PokemonCenter_1F_Text_CubonesMotherKilledByRockets::
    .string "I saw CUBONE's mother trying to\n"
    .string "escape from TEAM ROCKET.\p"
    .string "She was killed trying to get away…$"

LavenderTown_PokemonCenter_1F_Text_PeoplePayForCuboneSkulls::
    .string "You know how the CUBONE species\n"
    .string "wears skulls, right?\p"
    .string "People will pay a lot for one.$"

LavenderTown_PokemonCenter_1F_Text_WereYouTalkingToYourself::
    .string "…Were you talking to yourself\n"
    .string "back there?\p"
    .string "You're an odd kid, aren't you?$"

LavenderTown_PokemonCenter_1F_Text_SomeoneShouldDoSomething::
    .string "That POKéMON…\n"
    .string "The one in CERULEAN CAVE.\p"
    .string "I hear it's really dangerous, which\n"
    .string "is why the ELITE FOUR had to\l"
    .string "intervene, to keep it contained.\p"
    .string "It's so powerful, it even forced the\n"
    .string "other POKéMON in the cave to\l"
    .string "become powerful as well.\p"
    .string "Someone should probably do\n"
    .string "something about it…$"

LavenderTown_PokemonCenter_1F_Text_YouSawItButYouRanFromIt::
    .string "That POKéMON…\n"
    .string "The one in CERULEAN CAVE.\p"
    .string "…What's that? You say you saw it\n"
    .string "but you ran from it?\p"
    .string "Well, to be frank, I wouldn't\n"
    .string "wanna face it either…\l"
    .string "But someone has to do it.$"

LavenderTown_PokemonCenter_1F_Text_YouBeatItAndItRan::
    .string "That POKéMON…\n"
    .string "The one in CERULEAN CAVE.\p"
    .string "…What's that? You say you beat it\n"
    .string "and it ran from you?\p"
    .string "I'm not sure that's the best way\n"
    .string "to go about things…\p"
    .string "Perhaps it needs someone to show\n"
    .string "it some kindness, instead.\p"
    .string "Try going to the ELITE FOUR, maybe\n"
    .string "they'll give you some advice.\l"
    .string "You may even get another chance.$"

LavenderTown_PokemonCenter_1F_Text_ImNotSoSureIBelieveYou::
    .string "That POKéMON…\n"
    .string "The one in CERULEAN CAVE.\p"
    .string "…What's that? You say you actually\n"
    .string "caught it?\p"
    .string "I'm not so sure I believe you…$"

LavenderTown_PokemonCenter_1F_Text_NotYourMewtwo::
    .string "…! Is that…?\p"
    .string "Wait, this one isn't yours!\p"
    .string "Who are you trying to fool?$"

LavenderTown_PokemonCenter_1F_Text_YoureNotCheatingAreYou::
    .string "…! Is that…?\p"
    .string "Wait, how did you even get this\n"
    .string "one in the first place?\l"
    .string "You're not cheating, are you?$"

LavenderTown_PokemonCenter_1F_Text_SoYouManagedToCatchIt::
    .string "…! Is that…?\p"
    .string "So you managed to catch it\n"
    .string "after all…\p"
    .string "Maybe I misjudged you, I didn't\n"
    .string "trust you were really going to\l"
    .string "do it, but here you are.\p"
    .string "Perhaps you are worthy of\n"
    .string "knowing the truth, then.\p"
    .string "Here, take this.$"

LavenderTown_PokemonCenter_1F_Text_CarryingTooManyItems::
    .string "What the…?\p"
    .string "You're carrying too many items!$"

LavenderTown_PokemonCenter_1F_Text_ReceivedOldSeaMap::
    .string "{PLAYER} received the OLD SEA MAP\n"
    .string "from the mysterious guy!$"

LavenderTown_PokemonCenter_1F_Text_FindAWayToGetToThisIsland::
    .string "You should find a way to get\n"
    .string "to this island. Once you do,\l"
    .string "I believe you'll see the truth.\p"
    .string "…? You want to know my name?\p"
    .string "That shouldn't be too important.\p"
    .string "Well, I hope we can meet again\n"
    .string "some day! Good luck!$"

LavenderTown_PokemonCenter_1F_Text_TheMysteriousGuyDisappeared::
    .string "… … …?\p"
    .string "The mysterious guy disappeared!$"

