.set FEMALE_CLERK,   FLAG_TEMP_2

VermilionCity_Mart_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, VermilionCity_Mart_OnTransition
	.byte 0

VermilionCity_Mart_OnTransition::
	setflag FEMALE_CLERK
	end

VermilionCity_Mart_EventScript_CooltrainerF::
	msgbox VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer, MSGBOX_NPC
	end

VermilionCity_Mart_EventScript_BaldingMan::
	msgbox VermilionCity_Mart_Text_TeamRocketAreWickedPeople, MSGBOX_NPC
	end

VermilionCity_Mart_EventScript_Youngster::
	lock
	faceplayer
	checkplayergender
	goto_if_eq VAR_RESULT, FEMALE, VermilionCity_Mart_EventScript_YoungsterFemalePlayer
	msgbox VermilionCity_Mart_Text_ThatStoreClerkOverThere, MSGBOX_NPC
	release
	end

VermilionCity_Mart_EventScript_YoungsterFemalePlayer::
	msgbox VermilionCity_Mart_Text_WhereAreAllTheseGirlsComingFrom, MSGBOX_NPC
	release
	end

VermilionCity_Mart_EventScript_Clerk::
	goto_if_questlog EventScript_ReleaseEnd
	lock
	faceplayer
	message Text_MayIHelpYou
	waitmessage
	pokemart VermilionCity_Mart_Items
	msgbox Text_PleaseComeAgain
	release
	end

	.align 2
VermilionCity_Mart_Items::
	.2byte ITEM_POKE_BALL
	.2byte ITEM_SUPER_POTION
	.2byte ITEM_ANTIDOTE
	.2byte ITEM_PARALYZE_HEAL
	.2byte ITEM_AWAKENING
	.2byte ITEM_ICE_HEAL
	.2byte ITEM_REPEL
	.2byte ITEM_NONE
	release
	end
