VermilionCity_Mart_Text_TeamRocketAreWickedPeople::
    .string "There are wicked people who will\n"
    .string "use POKéMON for criminal acts.\p"
    .string "TEAM ROCKET traffics in rare\n"
    .string "POKéMON, for example.\p"
    .string "They also abandon POKéMON that\n"
    .string "they consider unpopular or useless.\p"
    .string "That's the sort of horrid people\n"
    .string "they are, TEAM ROCKET.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer::
    .string "I think POKéMON can be good or\n"
    .string "bad. It depends on the TRAINER.$"

VermilionCity_Mart_Text_ThatStoreClerkOverThere::
    .string "That store clerk over there…\n"
    .string "Isn't she pretty cute?\p"
    .string "I've just been looking around at\n"
    .string "the items for a while now since\l"
    .string "I'm too shy to go talk to her…\p"
    .string "I hope she doesn't notice it.$"

VermilionCity_Mart_Text_WhereAreAllTheseGirlsComingFrom::
    .string "Oh…\p"
    .string "H-hello!\p"
    .string "(Where are all these cute girls\n"
    .string "coming from?!)$"

