VermilionCity_Text_GrimerMultipliesInSludge::
    .string "We're careful about pollution here.\p"
    .string "We've heard GRIMER multiplies in\n"
    .string "toxic sludge.$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor::
    .string "Did you see the S.S. ANNE moored\n"
    .string "in the harbor?$"

VermilionCity_Text_SSAnneHasDepartedForYear::
    .string "So, the S.S. ANNE has departed?\p"
    .string "She'll be back in VERMILION about\n"
    .string "this time next year.$"

VermilionCity_Text_BuildingOnThisLand::
    .string "I'm putting up a building on this\n"
    .string "plot of land. I own it all.\p"
    .string "My POKéMON is tamping the land\n"
    .string "to lay the foundation.$"

VermilionCity_Text_Machop::
    .string "MACHOP: Guoh! Gogogoh!$"

VermilionCity_Text_MachopStompingLandFlat::
    .string "A MACHOP is stomping the land flat.$"

VermilionCity_Text_SSAnneVisitsOnceAYear::
    .string "The S.S. ANNE is a famous luxury\n"
    .string "cruise ship.\p"
    .string "It visits VERMILION once a year.$"

VermilionCity_Text_CitySign::
    .string "VERMILION CITY\n"
    .string "The Port of Exquisite Sunsets$"

VermilionCity_Text_SnorlaxBlockingRoute12::
    .string "NOTICE!\p"
    .string "ROUTE 12 may be blocked off by a\n"
    .string "sleeping POKéMON.\p"
    .string "Detour through ROCK TUNNEL to\n"
    .string "LAVENDER TOWN.\p"
    .string "VERMILION POLICE$"

VermilionCity_Text_PokemonFanClubSign::
    .string "POKéMON FAN CLUB\n"
    .string "All POKéMON fans welcome!$"

VermilionCity_Text_GymSign::
    .string "VERMILION CITY POKéMON GYM\n"
    .string "LEADER: LT. SURGE\l"
    .string "The Lightning American!$"

VermilionCity_Text_VermilionHarbor::
    .string "VERMILION HARBOR$"

VermilionCity_Text_WelcomeToTheSSAnne::
    .string "Welcome to the S.S. ANNE!$"

VermilionCity_Text_DoYouHaveATicket::
    .string "Welcome to the S.S. ANNE!\p"
    .string "Excuse me, do you have a ticket?$"

VermilionCity_Text_FlashedSSTicketColor::
    .string "{FONT_NORMAL}{COLOR DARK_GREY}{PLAYER} flashed the S.S. TICKET!\p"
    .string "{FONT_MALE}{COLOR BLUE}Great!\n"
    .string "Welcome to the S.S. ANNE!$"

VermilionCity_Text_FlashedSSTicketColorless::
    .string "{FONT_NORMAL}{PLAYER} flashed the S.S. TICKET!\p"
    .string "{FONT_MALE}Great!\n"
    .string "Welcome to the S.S. ANNE!$"

VermilionCity_Text_FlashedSSTicketColorInverted::
    .string "{FONT_NORMAL}{COLOR DARK_GREY}{PLAYER} flashed the S.S. TICKET!\p"
    .string "{FONT_MALE}{COLOR RED}Great!\n"
    .string "Welcome to the S.S. ANNE!$"

VermilionCity_Text_DontHaveNeededSSTicketColor::
    .string "{FONT_NORMAL}{COLOR DARK_GREY}{PLAYER} doesn't have the needed\n"
    .string "S.S. TICKET.\p"
    .string "{FONT_MALE}{COLOR BLUE}Sorry!\p"
    .string "You need a ticket to get aboard.$"

VermilionCity_Text_DontHaveNeededSSTicketColorless::
    .string "{FONT_NORMAL}{PLAYER} doesn't have the needed\n"
    .string "S.S. TICKET.\p"
    .string "{FONT_MALE}Sorry!\p"
    .string "You need a ticket to get aboard.$"

VermilionCity_Text_DontHaveNeededSSTicketColorInverted::
    .string "{FONT_NORMAL}{COLOR DARK_GREY}{PLAYER} doesn't have the needed\n"
    .string "S.S. TICKET.\p"
    .string "{FONT_MALE}{COLOR RED}Sorry!\p"
    .string "You need a ticket to get aboard.$"

VermilionCity_Text_TheShipSetSail::
    .string "The ship set sail.$"

VermilionCity_Text_BoardSeagallopTriPass::
    .string "Ah, you have a TRI-PASS.\p"
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"

VermilionCity_Text_Seagallop7Departing::
    .string "Okay, everything's in order.\p"
    .string "SEAGALLOP HI-SPEED 7 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_BoardSeagallopRainbowPass::
    .string "Ah, you have a RAINBOW PASS.\p"
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock::
    .string "Oh! That's a MYSTICTICKET!\n"
    .string "Now that is rare.\p"
    .string "We'll be happy to take you to\n"
    .string "NAVEL ROCK anytime.$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland::
    .string "Oh! That's an AURORATICKET!\n"
    .string "Now that is rare.\p"
    .string "We'll be happy to take you to\n"
    .string "BIRTH ISLAND anytime.$"

VermilionCity_Text_AhoyYouGotSomethingForMe::
    .string "Ahoy! You got something for me?\p"
    .string "…Hm? What is this?\n"
    .string "I can barely make it out.\p"
    .string "That's…! You're saying you want me\n"
    .string "to take you there?\p"
    .string "Sorry, but it's too far southwest!\n"
    .string "Even our best SEAGALLOP ferries\l"
    .string "would take far too long.\p"
    .string "You might need to ask someone else.$"

VermilionCity_Text_CaptainIsThatYou::
    .string "CAPTAIN! Is that you?\p"
    .string "I didn't think you'd be back so soon!\n"
    .string "Has the cruise been cancelled?\p"
    .string "$"

VermilionCity_Text_ThereHaveBeenComplications::
    .string "CAPTAIN: Oh, not at all!\p"
    .string "It's just that there have been\n"
    .string "some complications along the way,\l"
    .string "so we had make a detour back to\l"
    .string "VERMILION CITY.\p"
    .string "Is something the matter?\n"
    .string "I didn't interupt anything did I?$"

VermilionCity_Text_WhyIfItIsntPlayer::
    .string "Why, if it isn't the kid that\n"
    .string "helped me out that time!\p"
    .string "Sorry, didn't recognize you at first!\n"
    .string "Have you been doing well?\p"
    .string "… … …! That map…!\n"
    .string "I didn't think it still existed!\p"
    .string "$"

VermilionCity_Text_YouKnowOfThisMapCaptain::
    .string "You know of this map, CAPTAIN?\p"
    .string "$"

VermilionCity_Text_WellItsALongStory::
    .string "CAPTAIN: Well… It's a long story.\p"
    .string "$"

VermilionCity_Text_HowDidYouGetIt::
    .string "How did you get your hands on\n"
    .string "this, anyway?\p"
    .string "… …You know, I suppose it doesn't\n"
    .string "matter. I can see that you are a\l"
    .string "kind-hearted person. In fact…\p"
    .string "You wish to go there, don't you?\p"
    .string "Since you've helped me before, I\n"
    .string "think I'll do you another favor.\p"
    .string "You see, we actually own a special\n"
    .string "ferry, the SEAGALLOP HI-SPEED 15,\l"
    .string "which only a select few people\l"
    .string "know about, including myself.\p"
    .string "It should be able to take you\n"
    .string "there no problem.\p"
    .string "I'd be happy to take you there\n"
    .string "myself, but unfortunately, I must\l"
    .string "go back to the S.S. ANNE.\p"
    .string "$"

VermilionCity_Text_ThisSailorHowever::
    .string "This sailor here, however, is a good\n"
    .string "friend of mine, isn't that right?\p"
    .string "Here are the keys to the SEAGALLOP\n"
    .string "HI-SPEED 15.$"

VermilionCity_Text_IMustGoNow::
    .string "I must go now. Sorry I couldn't stay\n"
    .string "for longer…\p"
    .string "In fact, I only left to take a\n"
    .string "breather, haha! Rather nice timing\l"
    .string "on my part too, wouldn't you say?\p"
    .string "Well, good luck, you two!$"

VermilionCity_Text_WellYouHeardTheMan::
    .string "Well, you heard the man!\n"
    .string "Shall we get going?$"

VermilionCity_Text_BoardSeagallopFerry::
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"

VermilionCity_Text_Seagallop10Departing::
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry.\p"
    .string "SEAGALLOP HI-SPEED 10 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_Seagallop12Departing::
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry.\p"
    .string "SEAGALLOP HI-SPEED 12 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_Seagallop15Departing::
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry.\p"
    .string "SEAGALLOP HI-SPEED 15 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_Route2AideHasPackageForYou::
    .string "Oh, hello, {PLAYER}!\n"
    .string "How are you doing?\p"
    .string "It's me, one of PROF. OAK's AIDES.\p"
    .string "Did you meet the other AIDE?\p"
    .string "He had a package from PROF. OAK\n"
    .string "for you, {PLAYER}.\p"
    .string "He said he'd look for you around\n"
    .string "ROUTE 2, {PLAYER}.\p"
    .string "If you're in the ROUTE 2 area,\n"
    .string "please look for him.$"

