CinnabarIsland_Text_DoorIsLocked::
    .string "The door is locked…$"

CinnabarIsland_Text_BlaineLivedHereSinceBeforeLab::
    .string "CINNABAR GYM's BLAINE is quite the\n"
    .string "odd fellow.\p"
    .string "He's lived on the island since way\n"
    .string "before the LAB was built.$"

CinnabarIsland_Text_ScientistsExperimentInMansion::
    .string "Scientists conduct experiments\n"
    .string "in the burned-out building.\p"
    .string "You know, the one they call the\n"
    .string "POKéMON MANSION.$"

CinnabarIsland_Text_IslandSign::
    .string "CINNABAR ISLAND\n"
    .string "The Fiery Town of Burning Desire$"

CinnabarIsland_Text_PokemonLab::
    .string "POKéMON LAB$"

CinnabarIsland_Text_GymSign::
    .string "CINNABAR ISLAND POKéMON GYM\n"
    .string "LEADER: BLAINE\l"
    .string "The Hotheaded Quiz Master!$"

CinnabarIsland_Text_IslandsAreOneOfMyFavoriteThings::
    .string "Islands are one of my favorite\n"
    .string "things in the whole world.\p"
    .string "You know why?\p"
    .string "Well, because they're surrounded\n"
    .string "by water, of course!\p"
    .string "There's basically endless\n"
    .string "opportunity for fishing!\p"
    .string "Say, do you like fishing?$"

CinnabarIsland_Text_YouDoGrand::
    .string "You do? Grand!\p"
    .string "I'm glad I got to meet someone\n"
    .string "that shares my sentiment!\p"
    .string "$"

CinnabarIsland_Text_LikesFishingNoRod::
    .string "Do you have a fishing rod?\p"
    .string "No?! Why, you should, then!\p"
    .string "Here, take mine. No, really!$"

CinnabarIsland_Text_LikesFishingOldRod::
    .string "Do you have a fishing rod?\p"
    .string "Only that crummy OLD ROD?!\n"
    .string "Why, you ought to get a\l"
    .string "better one!\p"
    .string "Here, take mine. No, really!$"

CinnabarIsland_Text_YouDontHowCome::
    .string "You don't?! How come?\p"
    .string "Everyone should understand the\n"
    .string "wonders of fishing.\l"
    .string "You really should get into it!\p"
    .string "$"

CinnabarIsland_Text_DislikesFishingNoRod::
    .string "In fact, do you even own a\n"
    .string "fishing rod?\p"
    .string "No? Then how can you say you don't\n"
    .string "like fishing, without trying?\p"
    .string "Here, take mine. No, really!$"

CinnabarIsland_Text_DislikesFishingOldRod::
    .string "In fact, do you even own a\n"
    .string "fishing rod?\p"
    .string "Only that crummy OLD ROD?!\n"
    .string "Why, no wonder you dislike it,\l"
    .string "what can that one even do you?\p"
    .string "Here, take mine. No, really!$"

CinnabarIsland_Text_ReceivedGoodRod::
    .string "{PLAYER} received a GOOD ROD from\n"
    .string "the FISHERMAN.$"

CinnabarIsland_Text_ItDefinitelyIsntTheGreatest::
    .string "It definitely isn't the greatest,\n"
    .string "but it can help you, for sure!\p"
    .string "I have more at home, so don't\n"
    .string "worry about me!\p"
    .string "$"

CinnabarIsland_Text_WellBeSeeingYou::
    .string "Well, be seeing you!$"

CinnabarIsland_Text_SoIsMyGoodRodHelping::
    .string "So, is my GOOD ROD helping you out?$"

CinnabarIsland_Text_HeyIfItIsntPlayer::
    .string "Huh?\n"
    .string "Hey, if it isn't {PLAYER}!$"

CinnabarIsland_Text_ComeWithMeToOneIsland::
    .string "Look, it's me, BILL.\n"
    .string "Long time no see!\p"
    .string "I hope you're still using my\n"
    .string "PC system.\p"
    .string "Well, listen, since we met up here,\n"
    .string "how about spending time with me?\p"
    .string "There's this little island in the far\n"
    .string "south called ONE ISLAND.\p"
    .string "A friend invited me, so I'm on my\n"
    .string "way out there.\p"
    .string "How about it?\n"
    .string "Do you feel like coming with me?$"

CinnabarIsland_Text_AllRightLetsGo::
    .string "All right, then.\n"
    .string "Let's go!$"

CinnabarIsland_Text_IllBeWaitingInPokeCenter::
    .string "What, are you too busy?\p"
    .string "Well, all right.\n"
    .string "The boat hasn't arrived yet anyway.\p"
    .string "I'll be waiting at the POKéMON\n"
    .string "CENTER over there.\p"
    .string "Come see me when you're done with\n"
    .string "your business here.$"

CinnabarIsland_Text_MyPalsBoatArrived::
    .string "Looks like my pal's boat arrived,\n"
    .string "too.\p"
    .string "He sent it specially here to\n"
    .string "CINNABAR to pick me up.$"

CinnabarIsland_Text_IfYouHaveTriPassYouCanGoAgain::
    .string "Hey, wasn't that a long cruise?\p"
    .string "My buddy CELIO seemed to enjoy\n"
    .string "your company.\p"
    .string "I'm sure he'd welcome you if you\n"
    .string "were to visit him again.\p"
    .string "If you have a TRI-PASS, you can\n"
    .string "always take a ferry there from\l"
    .string "VERMILION PORT.\p"
    .string "All right, thanks for your company!$"

