CeladonCity_House1_Text_SlotsReelInTheDough::
    .string "Hehehe!\p"
    .string "The slots just reel in the dough,\n"
    .string "big-time!$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
    .string "CHIEF!\p"
    .string "We just shipped two thousand\n"
    .string "more POKéMON as slot prizes\l"
    .string "again today!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
    .string "Don't touch the poster at the GAME\n"
    .string "CORNER!\p"
    .string "There's no secret switch behind it!$"

CeladonCity_House1_Text_WhatDoYouWantKid::
    .string "What do you want, kid?\p"
    .string "I don't have time to play with you!$"

CeladonCity_House1_Text_CalmDownYouTwo::
    .string "Calm down, you two!\p"
    .string "At least the money's still rolling in!$"

CeladonCity_House1_Text_TheRocketsDisbanded::
    .string "The ROCKETS have disbanded!\p"
    .string "What do we do now?!$"

CeladonCity_House1_Text_DoYouHaveSomethingToDoWithThis::
    .string "You, kid!\p"
    .string "Do you have something to do\n"
    .string "with this?!$"

@ Text for the replaced altars in the rocket chiefs house / celadon mansion
@ In English RB, this is westernized as "It's a sculpture of DIGLETT.", and is removed altogether in FRLG
Text_ItsABuddhistAltar::
    .string "ぶつだん　だ‥$"
